"""
@Time       : 2026/07/22 05:16
@Author     : zhanglp8181
@File       : __init__.py
@CallChain  : app.sop_runtime 调用方 → 公共导出 → contracts/state_machine
@Description: 统一导出 SOP Runtime 的确定性契约与状态机接口。
"""

from app.sop_runtime.contracts import (
    BackoffStrategy,
    CommandEnvelope,
    CompletionMode,
    DeliveryStatus,
    DomainEventEnvelope,
    IdempotencyPolicy,
    IdempotencyScope,
    NodeExecutionStatus,
    OperationStatus,
    RetryPolicy,
    SopInstanceStatus,
    TimeoutAction,
    TimeoutPolicy,
    WorkItemCompletionPolicy,
    WorkItemStatus,
)
from app.sop_runtime.capabilities import (
    DEFAULT_CAPABILITY_REGISTRY,
    CapabilityAvailability,
    CapabilityRegistry,
    CapabilitySpec,
)
from app.sop_runtime.compatibility import (
    CompatibilityCandidate,
    CompatibilityEntry,
    CompatibilityReport,
    CompatibilityStatus,
    build_compatibility_report,
    render_compatibility_markdown,
)
from app.sop_runtime.condition_dsl import (
    CompiledCondition,
    CompiledConditionBranch,
    ConditionBranch,
    ConditionBranchSelectionResult,
    ConditionCompilationError,
    ConditionDsl,
    ConditionErrorCode,
    ConditionEvaluationResult,
    ConditionOperator,
    compile_condition_dsl,
    compile_condition_branches,
    evaluate_condition,
    parse_condition_dsl,
    select_condition_branch,
    validate_condition_branches,
)
from app.sop_runtime.definition import (
    AuthenticatedEmployeeAttribute,
    AuthenticatedInputBinding,
    CanonicalEdge,
    CompilationDiagnostic,
    CompiledSopDefinition,
    DiagnosticSeverity,
    ExplicitConfirmationPolicy,
    InputBindingSource,
    NodeType,
    ParticipantScopeResolver,
)
from app.sop_runtime.legacy_skill_card_adapter import (
    LEGACY_SKILL_CARD_SCHEMA_VERSION,
    SopCompilationError,
    compile_legacy_skill_card,
)
from app.sop_runtime.state_machine import (
    RevisionConflictError,
    StateTransitionError,
    TransitionResult,
    transition_delivery,
    transition_instance,
    transition_node,
    transition_operation,
    transition_work_item,
)

__all__ = [
    "AuthenticatedEmployeeAttribute",
    "AuthenticatedInputBinding",
    "BackoffStrategy",
    "CanonicalEdge",
    "CapabilityRegistry",
    "CapabilitySpec",
    "CapabilityAvailability",
    "CommandEnvelope",
    "CompilationDiagnostic",
    "CompiledSopDefinition",
    "CompiledCondition",
    "CompiledConditionBranch",
    "CompatibilityCandidate",
    "CompatibilityEntry",
    "CompatibilityReport",
    "CompatibilityStatus",
    "CompletionMode",
    "ConditionBranch",
    "ConditionBranchSelectionResult",
    "ConditionCompilationError",
    "ConditionDsl",
    "ConditionErrorCode",
    "ConditionEvaluationResult",
    "ConditionOperator",
    "DEFAULT_CAPABILITY_REGISTRY",
    "DeliveryStatus",
    "DomainEventEnvelope",
    "ExplicitConfirmationPolicy",
    "IdempotencyPolicy",
    "IdempotencyScope",
    "InputBindingSource",
    "LEGACY_SKILL_CARD_SCHEMA_VERSION",
    "NodeExecutionStatus",
    "NodeType",
    "ParticipantScopeResolver",
    "OperationStatus",
    "RetryPolicy",
    "RevisionConflictError",
    "SopInstanceStatus",
    "SopCompilationError",
    "StateTransitionError",
    "TimeoutAction",
    "TimeoutPolicy",
    "TransitionResult",
    "WorkItemCompletionPolicy",
    "WorkItemStatus",
    "DiagnosticSeverity",
    "compile_legacy_skill_card",
    "compile_condition_dsl",
    "compile_condition_branches",
    "build_compatibility_report",
    "render_compatibility_markdown",
    "evaluate_condition",
    "parse_condition_dsl",
    "select_condition_branch",
    "transition_delivery",
    "transition_instance",
    "transition_node",
    "transition_operation",
    "transition_work_item",
    "validate_condition_branches",
]
