# ruff: noqa
"""mysql baseline

Revision ID: 20260718_0001
Revises: 
Create Date: 2026-07-18 08:37:44.403943
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '20260718_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_events_session_id'), 'agent_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_events_tenant_id'), 'agent_events', ['tenant_id'], unique=False)
    op.create_table('agent_knowledge_branches',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('base_version', sa.String(length=64), nullable=False),
    sa.Column('head_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('sync_state', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'knowledge_base_id', name='uq_agent_knowledge_branch')
    )
    op.create_index(op.f('ix_agent_knowledge_branches_agent_id'), 'agent_knowledge_branches', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_branches_knowledge_base_id'), 'agent_knowledge_branches', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_branches_status'), 'agent_knowledge_branches', ['status'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_branches_sync_state'), 'agent_knowledge_branches', ['sync_state'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_branches_tenant_id'), 'agent_knowledge_branches', ['tenant_id'], unique=False)
    op.create_table('agent_model_bindings',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('model_config_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'role', name='uq_agent_model_binding')
    )
    op.create_index(op.f('ix_agent_model_bindings_agent_id'), 'agent_model_bindings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_model_bindings_model_config_id'), 'agent_model_bindings', ['model_config_id'], unique=False)
    op.create_index(op.f('ix_agent_model_bindings_role'), 'agent_model_bindings', ['role'], unique=False)
    op.create_index(op.f('ix_agent_model_bindings_tenant_id'), 'agent_model_bindings', ['tenant_id'], unique=False)
    op.create_table('agent_profiles',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('persona_prompt', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('is_overall', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_agent_profile_tenant_name')
    )
    op.create_index(op.f('ix_agent_profiles_is_overall'), 'agent_profiles', ['is_overall'], unique=False)
    op.create_index(op.f('ix_agent_profiles_status'), 'agent_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_agent_profiles_tenant_id'), 'agent_profiles', ['tenant_id'], unique=False)
    op.create_table('agent_resource_bindings',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'resource_type', 'resource_id', name='uq_agent_resource')
    )
    op.create_index(op.f('ix_agent_resource_bindings_agent_id'), 'agent_resource_bindings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_resource_bindings_resource_id'), 'agent_resource_bindings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_agent_resource_bindings_resource_type'), 'agent_resource_bindings', ['resource_type'], unique=False)
    op.create_index(op.f('ix_agent_resource_bindings_status'), 'agent_resource_bindings', ['status'], unique=False)
    op.create_index(op.f('ix_agent_resource_bindings_tenant_id'), 'agent_resource_bindings', ['tenant_id'], unique=False)
    op.create_table('agent_skill_branch_versions',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('source_skill_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('base_version', sa.String(length=64), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('sync_state', sa.String(length=64), nullable=False),
    sa.Column('change_summary', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'skill_id', 'version', name='uq_agent_skill_branch_version')
    )
    op.create_index(op.f('ix_agent_skill_branch_versions_agent_id'), 'agent_skill_branch_versions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_branch_versions_skill_id'), 'agent_skill_branch_versions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_branch_versions_source_skill_id'), 'agent_skill_branch_versions', ['source_skill_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_branch_versions_status'), 'agent_skill_branch_versions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_skill_branch_versions_sync_state'), 'agent_skill_branch_versions', ['sync_state'], unique=False)
    op.create_index(op.f('ix_agent_skill_branch_versions_tenant_id'), 'agent_skill_branch_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_branch_versions_version'), 'agent_skill_branch_versions', ['version'], unique=False)
    op.create_table('agent_skill_branches',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('source_skill_id', sa.String(length=128), nullable=False),
    sa.Column('base_version', sa.String(length=64), nullable=False),
    sa.Column('head_version', sa.String(length=64), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('sync_state', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'skill_id', name='uq_agent_skill_branch')
    )
    op.create_index(op.f('ix_agent_skill_branches_agent_id'), 'agent_skill_branches', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_branches_skill_id'), 'agent_skill_branches', ['skill_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_branches_source_skill_id'), 'agent_skill_branches', ['source_skill_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_branches_status'), 'agent_skill_branches', ['status'], unique=False)
    op.create_index(op.f('ix_agent_skill_branches_sync_state'), 'agent_skill_branches', ['sync_state'], unique=False)
    op.create_index(op.f('ix_agent_skill_branches_tenant_id'), 'agent_skill_branches', ['tenant_id'], unique=False)
    op.create_table('agent_usages',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'agent_id', name='uq_agent_usage_user_agent')
    )
    op.create_index(op.f('ix_agent_usages_agent_id'), 'agent_usages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_usages_tenant_id'), 'agent_usages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_usages_user_id'), 'agent_usages', ['user_id'], unique=False)
    op.create_table('general_skills',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('skill_markdown', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('skill_files_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('permissions_json', sa.JSON(), nullable=True),
    sa.Column('runtime_config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_general_skill_tenant_slug')
    )
    op.create_index(op.f('ix_general_skills_slug'), 'general_skills', ['slug'], unique=False)
    op.create_index(op.f('ix_general_skills_status'), 'general_skills', ['status'], unique=False)
    op.create_index(op.f('ix_general_skills_tenant_id'), 'general_skills', ['tenant_id'], unique=False)
    op.create_table('human_handoff_requests',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('requester_user_id', sa.String(length=128), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=128), nullable=True),
    sa.Column('trigger_skill_id', sa.String(length=128), nullable=True),
    sa.Column('trigger_step_id', sa.String(length=128), nullable=True),
    sa.Column('context_summary', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('pending_question', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('human_reply', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('resume_payload_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_handoff_requests_agent_id'), 'human_handoff_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_human_handoff_requests_assignee_user_id'), 'human_handoff_requests', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_human_handoff_requests_requester_user_id'), 'human_handoff_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_human_handoff_requests_session_id'), 'human_handoff_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_human_handoff_requests_status'), 'human_handoff_requests', ['status'], unique=False)
    op.create_index(op.f('ix_human_handoff_requests_tenant_id'), 'human_handoff_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_human_handoff_requests_trigger_skill_id'), 'human_handoff_requests', ['trigger_skill_id'], unique=False)
    op.create_index(op.f('ix_human_handoff_requests_trigger_step_id'), 'human_handoff_requests', ['trigger_step_id'], unique=False)
    op.create_table('knowledge_base_versions',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'knowledge_base_id', 'version', name='uq_knowledge_base_version')
    )
    op.create_index(op.f('ix_knowledge_base_versions_knowledge_base_id'), 'knowledge_base_versions', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_status'), 'knowledge_base_versions', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_tenant_id'), 'knowledge_base_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_versions_version'), 'knowledge_base_versions', ['version'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_knowledge_base_tenant_name')
    )
    op.create_index(op.f('ix_knowledge_bases_status'), 'knowledge_bases', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_tenant_id'), 'knowledge_bases', ['tenant_id'], unique=False)
    op.create_table('knowledge_buckets',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_version_id', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_key', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('summary', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_buckets_bucket_key'), 'knowledge_buckets', ['bucket_key'], unique=False)
    op.create_index(op.f('ix_knowledge_buckets_document_id'), 'knowledge_buckets', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_buckets_knowledge_base_id'), 'knowledge_buckets', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_buckets_knowledge_base_version_id'), 'knowledge_buckets', ['knowledge_base_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_buckets_tenant_id'), 'knowledge_buckets', ['tenant_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_version_id', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('summary', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('source_ref', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_bucket_id'), 'knowledge_chunks', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_chunk_index'), 'knowledge_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_knowledge_base_id'), 'knowledge_chunks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_knowledge_base_version_id'), 'knowledge_chunks', ['knowledge_base_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_tenant_id'), 'knowledge_chunks', ['tenant_id'], unique=False)
    op.create_table('knowledge_concepts',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_version_id', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=True),
    sa.Column('concept_id', sa.String(length=128), nullable=False),
    sa.Column('concept_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('content_md', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('frontmatter_json', sa.JSON(), nullable=True),
    sa.Column('links_json', sa.JSON(), nullable=True),
    sa.Column('citations_json', sa.JSON(), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'knowledge_base_version_id', 'concept_id', name='uq_knowledge_concept_version_path')
    )
    op.create_index(op.f('ix_knowledge_concepts_concept_id'), 'knowledge_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_knowledge_concepts_concept_type'), 'knowledge_concepts', ['concept_type'], unique=False)
    op.create_index(op.f('ix_knowledge_concepts_document_id'), 'knowledge_concepts', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_concepts_knowledge_base_id'), 'knowledge_concepts', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_concepts_knowledge_base_version_id'), 'knowledge_concepts', ['knowledge_base_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_concepts_status'), 'knowledge_concepts', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_concepts_tenant_id'), 'knowledge_concepts', ['tenant_id'], unique=False)
    op.create_table('knowledge_discovery_suggestions',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_version_id', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=True),
    sa.Column('suggestion_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_discovery_suggestions_bucket_id'), 'knowledge_discovery_suggestions', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_knowledge_discovery_suggestions_document_id'), 'knowledge_discovery_suggestions', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_discovery_suggestions_knowledge_base_id'), 'knowledge_discovery_suggestions', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_discovery_suggestions_knowledge_base_version_id'), 'knowledge_discovery_suggestions', ['knowledge_base_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_discovery_suggestions_status'), 'knowledge_discovery_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_discovery_suggestions_suggestion_type'), 'knowledge_discovery_suggestions', ['suggestion_type'], unique=False)
    op.create_index(op.f('ix_knowledge_discovery_suggestions_tenant_id'), 'knowledge_discovery_suggestions', ['tenant_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_version_id', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=191), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('bucket_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_file_type'), 'knowledge_documents', ['file_type'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_version_id'), 'knowledge_documents', ['knowledge_base_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_tenant_id'), 'knowledge_documents', ['tenant_id'], unique=False)
    op.create_table('knowledge_ingest_jobs',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=False),
    sa.Column('knowledge_base_version_id', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=191), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_ingest_jobs_document_id'), 'knowledge_ingest_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_knowledge_base_id'), 'knowledge_ingest_jobs', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_knowledge_base_version_id'), 'knowledge_ingest_jobs', ['knowledge_base_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_status'), 'knowledge_ingest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_tenant_id'), 'knowledge_ingest_jobs', ['tenant_id'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=191), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('args_json', sa.JSON(), nullable=True),
    sa.Column('env_json', sa.JSON(), nullable=True),
    sa.Column('cwd', sa.Text(), nullable=True),
    sa.Column('discovered_tools_json', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_mcp_server_tenant_name')
    )
    op.create_index(op.f('ix_mcp_servers_bucket'), 'mcp_servers', ['bucket'], unique=False)
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=False)
    op.create_index(op.f('ix_mcp_servers_tenant_id'), 'mcp_servers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mcp_servers_transport'), 'mcp_servers', ['transport'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=191), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_kind'), 'memories', ['kind'], unique=False)
    op.create_index(op.f('ix_memories_session_id'), 'memories', ['session_id'], unique=False)
    op.create_index(op.f('ix_memories_tenant_id'), 'memories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_memories_username'), 'memories', ['username'], unique=False)
    op.create_table('message_feedback',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.String(length=64), nullable=False),
    sa.Column('analysis_status', sa.String(length=64), nullable=False),
    sa.Column('analysis_bucket', sa.String(length=64), nullable=True),
    sa.Column('analysis_reason', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('analysis_summary', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'message_id', 'user_id', name='uq_feedback_message_user')
    )
    op.create_index(op.f('ix_message_feedback_analysis_bucket'), 'message_feedback', ['analysis_bucket'], unique=False)
    op.create_index(op.f('ix_message_feedback_analysis_status'), 'message_feedback', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_rating'), 'message_feedback', ['rating'], unique=False)
    op.create_index(op.f('ix_message_feedback_session_id'), 'message_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_tenant_id'), 'message_feedback', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_user_id'), 'message_feedback', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_table('mock_orders',
    sa.Column('order_id', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.String(length=191), nullable=True),
    sa.Column('sku_id', sa.String(length=191), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payment_status', sa.String(length=64), nullable=True),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.Column('signed_days', sa.Integer(), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_mock_orders_product_id'), 'mock_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_mock_orders_status'), 'mock_orders', ['status'], unique=False)
    op.create_index(op.f('ix_mock_orders_user_id'), 'mock_orders', ['user_id'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('model', sa.String(length=191), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('extra_body_json', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_tenant_id'), 'model_configs', ['tenant_id'], unique=False)
    op.create_table('persona_configs',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('scheduled_task_runs',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('scheduled_task_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('error', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('trace_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_task_id', 'scheduled_for', name='uq_scheduled_task_run_due_time')
    )
    op.create_index(op.f('ix_scheduled_task_runs_agent_id'), 'scheduled_task_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_finished_at'), 'scheduled_task_runs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_scheduled_for'), 'scheduled_task_runs', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_scheduled_task_id'), 'scheduled_task_runs', ['scheduled_task_id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_session_id'), 'scheduled_task_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_started_at'), 'scheduled_task_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_status'), 'scheduled_task_runs', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_tenant_id'), 'scheduled_task_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_runs_user_id'), 'scheduled_task_runs', ['user_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('prompt', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('schedule_type', sa.String(length=64), nullable=False),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=191), nullable=False),
    sa.Column('rrule', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('concurrency_policy', sa.String(length=64), nullable=False),
    sa.Column('misfire_policy', sa.String(length=64), nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=64), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('source_session_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_agent_id'), 'scheduled_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_concurrency_policy'), 'scheduled_tasks', ['concurrency_policy'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_created_by_user_id'), 'scheduled_tasks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_end_at'), 'scheduled_tasks', ['end_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_last_run_at'), 'scheduled_tasks', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_last_status'), 'scheduled_tasks', ['last_status'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_lease_owner'), 'scheduled_tasks', ['lease_owner'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_lease_until'), 'scheduled_tasks', ['lease_until'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_misfire_policy'), 'scheduled_tasks', ['misfire_policy'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_next_run_at'), 'scheduled_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_schedule_type'), 'scheduled_tasks', ['schedule_type'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_source_session_id'), 'scheduled_tasks', ['source_session_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_status'), 'scheduled_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_tenant_id'), 'scheduled_tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_timezone'), 'scheduled_tasks', ['timezone'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=191), nullable=True),
    sa.Column('active_skill_id', sa.String(length=128), nullable=True),
    sa.Column('active_step_id', sa.String(length=128), nullable=True),
    sa.Column('slots_json', sa.JSON(), nullable=True),
    sa.Column('skill_stack_json', sa.JSON(), nullable=True),
    sa.Column('pending_tasks_json', sa.JSON(), nullable=True),
    sa.Column('resume_after_answer_json', sa.JSON(), nullable=True),
    sa.Column('awaiting_input_json', sa.JSON(), nullable=True),
    sa.Column('knowledge_context_json', sa.JSON(), nullable=True),
    sa.Column('context_state_json', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('last_agent_question', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_agent_id'), 'sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('skill_feedback',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('skill_version', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'message_id', 'user_id', name='uq_skill_feedback_message_user')
    )
    op.create_index(op.f('ix_skill_feedback_message_id'), 'skill_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_skill_feedback_rating'), 'skill_feedback', ['rating'], unique=False)
    op.create_index(op.f('ix_skill_feedback_session_id'), 'skill_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_skill_feedback_skill_id'), 'skill_feedback', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_feedback_skill_version'), 'skill_feedback', ['skill_version'], unique=False)
    op.create_index(op.f('ix_skill_feedback_step_id'), 'skill_feedback', ['step_id'], unique=False)
    op.create_index(op.f('ix_skill_feedback_tenant_id'), 'skill_feedback', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_skill_feedback_user_id'), 'skill_feedback', ['user_id'], unique=False)
    op.create_table('skill_versions',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('business_domain', sa.String(length=191), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'skill_id', 'version', name='uq_skill_version')
    )
    op.create_index(op.f('ix_skill_versions_skill_id'), 'skill_versions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_versions_status'), 'skill_versions', ['status'], unique=False)
    op.create_index(op.f('ix_skill_versions_tenant_id'), 'skill_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_skill_versions_version'), 'skill_versions', ['version'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('business_domain', sa.String(length=191), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'skill_id', name='uq_skill_tenant_skill_id')
    )
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skills_status'), 'skills', ['status'], unique=False)
    op.create_index(op.f('ix_skills_tenant_id'), 'skills', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=191), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('tool_type', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('auth_json', sa.JSON(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('allowed_skills_json', sa.JSON(), nullable=True),
    sa.Column('mcp_server_id', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tool_tenant_name')
    )
    op.create_index(op.f('ix_tools_bucket'), 'tools', ['bucket'], unique=False)
    op.create_index(op.f('ix_tools_mcp_server_id'), 'tools', ['mcp_server_id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_index(op.f('ix_tools_tenant_id'), 'tools', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tools_tool_type'), 'tools', ['tool_type'], unique=False)
    op.create_table('ui_configs',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('show_thinking_trace', sa.Boolean(), nullable=False),
    sa.Column('show_skill_trace', sa.Boolean(), nullable=False),
    sa.Column('show_tool_trace', sa.Boolean(), nullable=False),
    sa.Column('reflection_max_rounds', sa.Integer(), nullable=False),
    sa.Column('agent_loop_max_actions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=191), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_user_tenant_username')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('ui_configs')
    op.drop_index(op.f('ix_tools_tool_type'), table_name='tools')
    op.drop_index(op.f('ix_tools_tenant_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_mcp_server_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_bucket'), table_name='tools')
    op.drop_table('tools')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_skills_tenant_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_status'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_skill_versions_version'), table_name='skill_versions')
    op.drop_index(op.f('ix_skill_versions_tenant_id'), table_name='skill_versions')
    op.drop_index(op.f('ix_skill_versions_status'), table_name='skill_versions')
    op.drop_index(op.f('ix_skill_versions_skill_id'), table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index(op.f('ix_skill_feedback_user_id'), table_name='skill_feedback')
    op.drop_index(op.f('ix_skill_feedback_tenant_id'), table_name='skill_feedback')
    op.drop_index(op.f('ix_skill_feedback_step_id'), table_name='skill_feedback')
    op.drop_index(op.f('ix_skill_feedback_skill_version'), table_name='skill_feedback')
    op.drop_index(op.f('ix_skill_feedback_skill_id'), table_name='skill_feedback')
    op.drop_index(op.f('ix_skill_feedback_session_id'), table_name='skill_feedback')
    op.drop_index(op.f('ix_skill_feedback_rating'), table_name='skill_feedback')
    op.drop_index(op.f('ix_skill_feedback_message_id'), table_name='skill_feedback')
    op.drop_table('skill_feedback')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_agent_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scheduled_tasks_timezone'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_tenant_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_status'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_source_session_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_schedule_type'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_next_run_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_misfire_policy'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_lease_until'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_lease_owner'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_last_status'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_last_run_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_end_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_created_by_user_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_concurrency_policy'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_agent_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_task_runs_user_id'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_tenant_id'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_status'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_started_at'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_session_id'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_scheduled_task_id'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_scheduled_for'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_finished_at'), table_name='scheduled_task_runs')
    op.drop_index(op.f('ix_scheduled_task_runs_agent_id'), table_name='scheduled_task_runs')
    op.drop_table('scheduled_task_runs')
    op.drop_table('persona_configs')
    op.drop_index(op.f('ix_model_configs_tenant_id'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_mock_orders_user_id'), table_name='mock_orders')
    op.drop_index(op.f('ix_mock_orders_status'), table_name='mock_orders')
    op.drop_index(op.f('ix_mock_orders_product_id'), table_name='mock_orders')
    op.drop_table('mock_orders')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_message_feedback_user_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_tenant_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_session_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_rating'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_analysis_status'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_analysis_bucket'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_index(op.f('ix_memories_username'), table_name='memories')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_tenant_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_session_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_kind'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_mcp_servers_transport'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_tenant_id'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_name'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_bucket'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_tenant_id'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_status'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_knowledge_base_version_id'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_knowledge_base_id'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_document_id'), table_name='knowledge_ingest_jobs')
    op.drop_table('knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_documents_tenant_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_version_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_file_type'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_discovery_suggestions_tenant_id'), table_name='knowledge_discovery_suggestions')
    op.drop_index(op.f('ix_knowledge_discovery_suggestions_suggestion_type'), table_name='knowledge_discovery_suggestions')
    op.drop_index(op.f('ix_knowledge_discovery_suggestions_status'), table_name='knowledge_discovery_suggestions')
    op.drop_index(op.f('ix_knowledge_discovery_suggestions_knowledge_base_version_id'), table_name='knowledge_discovery_suggestions')
    op.drop_index(op.f('ix_knowledge_discovery_suggestions_knowledge_base_id'), table_name='knowledge_discovery_suggestions')
    op.drop_index(op.f('ix_knowledge_discovery_suggestions_document_id'), table_name='knowledge_discovery_suggestions')
    op.drop_index(op.f('ix_knowledge_discovery_suggestions_bucket_id'), table_name='knowledge_discovery_suggestions')
    op.drop_table('knowledge_discovery_suggestions')
    op.drop_index(op.f('ix_knowledge_concepts_tenant_id'), table_name='knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_concepts_status'), table_name='knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_concepts_knowledge_base_version_id'), table_name='knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_concepts_knowledge_base_id'), table_name='knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_concepts_document_id'), table_name='knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_concepts_concept_type'), table_name='knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_concepts_concept_id'), table_name='knowledge_concepts')
    op.drop_table('knowledge_concepts')
    op.drop_index(op.f('ix_knowledge_chunks_tenant_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_base_version_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_base_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_chunk_index'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_bucket_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_buckets_tenant_id'), table_name='knowledge_buckets')
    op.drop_index(op.f('ix_knowledge_buckets_knowledge_base_version_id'), table_name='knowledge_buckets')
    op.drop_index(op.f('ix_knowledge_buckets_knowledge_base_id'), table_name='knowledge_buckets')
    op.drop_index(op.f('ix_knowledge_buckets_document_id'), table_name='knowledge_buckets')
    op.drop_index(op.f('ix_knowledge_buckets_bucket_key'), table_name='knowledge_buckets')
    op.drop_table('knowledge_buckets')
    op.drop_index(op.f('ix_knowledge_bases_tenant_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_status'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_knowledge_base_versions_version'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_tenant_id'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_status'), table_name='knowledge_base_versions')
    op.drop_index(op.f('ix_knowledge_base_versions_knowledge_base_id'), table_name='knowledge_base_versions')
    op.drop_table('knowledge_base_versions')
    op.drop_index(op.f('ix_human_handoff_requests_trigger_step_id'), table_name='human_handoff_requests')
    op.drop_index(op.f('ix_human_handoff_requests_trigger_skill_id'), table_name='human_handoff_requests')
    op.drop_index(op.f('ix_human_handoff_requests_tenant_id'), table_name='human_handoff_requests')
    op.drop_index(op.f('ix_human_handoff_requests_status'), table_name='human_handoff_requests')
    op.drop_index(op.f('ix_human_handoff_requests_session_id'), table_name='human_handoff_requests')
    op.drop_index(op.f('ix_human_handoff_requests_requester_user_id'), table_name='human_handoff_requests')
    op.drop_index(op.f('ix_human_handoff_requests_assignee_user_id'), table_name='human_handoff_requests')
    op.drop_index(op.f('ix_human_handoff_requests_agent_id'), table_name='human_handoff_requests')
    op.drop_table('human_handoff_requests')
    op.drop_index(op.f('ix_general_skills_tenant_id'), table_name='general_skills')
    op.drop_index(op.f('ix_general_skills_status'), table_name='general_skills')
    op.drop_index(op.f('ix_general_skills_slug'), table_name='general_skills')
    op.drop_table('general_skills')
    op.drop_index(op.f('ix_agent_usages_user_id'), table_name='agent_usages')
    op.drop_index(op.f('ix_agent_usages_tenant_id'), table_name='agent_usages')
    op.drop_index(op.f('ix_agent_usages_agent_id'), table_name='agent_usages')
    op.drop_table('agent_usages')
    op.drop_index(op.f('ix_agent_skill_branches_tenant_id'), table_name='agent_skill_branches')
    op.drop_index(op.f('ix_agent_skill_branches_sync_state'), table_name='agent_skill_branches')
    op.drop_index(op.f('ix_agent_skill_branches_status'), table_name='agent_skill_branches')
    op.drop_index(op.f('ix_agent_skill_branches_source_skill_id'), table_name='agent_skill_branches')
    op.drop_index(op.f('ix_agent_skill_branches_skill_id'), table_name='agent_skill_branches')
    op.drop_index(op.f('ix_agent_skill_branches_agent_id'), table_name='agent_skill_branches')
    op.drop_table('agent_skill_branches')
    op.drop_index(op.f('ix_agent_skill_branch_versions_version'), table_name='agent_skill_branch_versions')
    op.drop_index(op.f('ix_agent_skill_branch_versions_tenant_id'), table_name='agent_skill_branch_versions')
    op.drop_index(op.f('ix_agent_skill_branch_versions_sync_state'), table_name='agent_skill_branch_versions')
    op.drop_index(op.f('ix_agent_skill_branch_versions_status'), table_name='agent_skill_branch_versions')
    op.drop_index(op.f('ix_agent_skill_branch_versions_source_skill_id'), table_name='agent_skill_branch_versions')
    op.drop_index(op.f('ix_agent_skill_branch_versions_skill_id'), table_name='agent_skill_branch_versions')
    op.drop_index(op.f('ix_agent_skill_branch_versions_agent_id'), table_name='agent_skill_branch_versions')
    op.drop_table('agent_skill_branch_versions')
    op.drop_index(op.f('ix_agent_resource_bindings_tenant_id'), table_name='agent_resource_bindings')
    op.drop_index(op.f('ix_agent_resource_bindings_status'), table_name='agent_resource_bindings')
    op.drop_index(op.f('ix_agent_resource_bindings_resource_type'), table_name='agent_resource_bindings')
    op.drop_index(op.f('ix_agent_resource_bindings_resource_id'), table_name='agent_resource_bindings')
    op.drop_index(op.f('ix_agent_resource_bindings_agent_id'), table_name='agent_resource_bindings')
    op.drop_table('agent_resource_bindings')
    op.drop_index(op.f('ix_agent_profiles_tenant_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_status'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_is_overall'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    op.drop_index(op.f('ix_agent_model_bindings_tenant_id'), table_name='agent_model_bindings')
    op.drop_index(op.f('ix_agent_model_bindings_role'), table_name='agent_model_bindings')
    op.drop_index(op.f('ix_agent_model_bindings_model_config_id'), table_name='agent_model_bindings')
    op.drop_index(op.f('ix_agent_model_bindings_agent_id'), table_name='agent_model_bindings')
    op.drop_table('agent_model_bindings')
    op.drop_index(op.f('ix_agent_knowledge_branches_tenant_id'), table_name='agent_knowledge_branches')
    op.drop_index(op.f('ix_agent_knowledge_branches_sync_state'), table_name='agent_knowledge_branches')
    op.drop_index(op.f('ix_agent_knowledge_branches_status'), table_name='agent_knowledge_branches')
    op.drop_index(op.f('ix_agent_knowledge_branches_knowledge_base_id'), table_name='agent_knowledge_branches')
    op.drop_index(op.f('ix_agent_knowledge_branches_agent_id'), table_name='agent_knowledge_branches')
    op.drop_table('agent_knowledge_branches')
    op.drop_index(op.f('ix_agent_events_tenant_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_session_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
