export enum EnterpriseRoute {
  Workspace = '/workspace',
  Chat = '/workspace/chat',
  Platform = '/enterprise/platform',
  Gallery = '/workspace/gallery',
  Agents = '/enterprise/agents',
  Dashboard = '/enterprise/dashboard',
  Persona = '/enterprise/persona',
  ScheduledTasks = '/enterprise/scheduled-tasks',
  Memories = '/enterprise/memories',
  Feedback = '/enterprise/feedback',
  Knowledge = '/enterprise/knowledge',
  GeneralSkills = '/enterprise/general-skills',
  Skills = '/enterprise/skills',
  Tools = '/enterprise/tools',
  WorkItems = '/enterprise/work-items',
  Accounts = '/enterprise/accounts',
  Organization = '/enterprise/organization',
  EnterpriseInfo = '/enterprise/enterprise-info',
  ReferenceData = '/enterprise/reference-data',
  OrganizationRoles = '/enterprise/organization-roles',
  ManagementAudit = '/enterprise/management-audit',
  Models = '/enterprise/models',
  Connections = '/enterprise/connections',
}
